### ISSUE TITLE
Exporting to different file formats

### ISSUE THREAD

**Issue by myuce** [LordVonAdel/source-mdl#1]
Would it be possible to add support for different file formats other than gltf? I'm working on a map converter that converts Source Engine maps to a different map format, so it'd be really useful to be able to export to Wavefront obj format.

**Comment by LordVonAdel** [comment]
After calling `model.import()` you can get the raw data with `model.getData()`. It is an object containing all data about vertices and stuff structured similarly to the source mdl file. From there you can build your own exporter. 

I think I will start in the next week or so to implement the option for exporting obj.

**Comment by myuce** [comment]
Glad to hear that. I'll try writing my own exporter to understand both formats better and see how it goes.

**Comment by LordVonAdel** [comment]
OBJ export is now implemented 84fccc4153a04c93f1f82920a9319c8ec99e7449.
